console.log(process.env.NETLIFY)
console.log(process.env.CONTEXT)
console.log('process.env.BRANCH', process.env.BRANCH)
console.log('process.env.REPOSITORY_URL', process.env.REPOSITORY_URL)
console.log('process.env.HEAD', process.env.HEAD)
console.log('process.env.PULL_REQUEST', process.env.PULL_REQUEST)
